#!/usr/bin/env Rscript

###########################
## DARRAGH NIMMO
## JANUARY 2021
## ATACseqQC plots for ATAC-seq quality assessment
##########################


###################################################################################################################################################
#####LOAD PACKAGES
###################################################################################################################################################
#library(motifStack)
library(ATACseqQC)
library(TxDb.Hsapiens.UCSC.hg38.knownGene)
library(BSgenome.Hsapiens.UCSC.hg38)
library(phastCons100way.UCSC.hg38)

#library(MotifDb)
#library(ChIPpeakAnno)
#library(GenomicAlignments)


######################################################################################################################################################
#####SET UP VARIABLES AND PATHS
######################################################################################################################################################
args = commandArgs(trailingOnly=TRUE)
bamfile = args[1]
bamfile.sample.ID = gsub(".bam", "", basename(bamfile))

possibleTag = combn(LETTERS, 2)
possibleTag = c(paste0(possibleTag[1, ], possibleTag[2, ]),
                 paste0(possibleTag[2, ], possibleTag[1, ]))
bamTop100 = scanBam(BamFile(bamfile, yieldSize = 100),
                     param = ScanBamParam(tag = possibleTag))[[1]]$tag

tags = names(bamTop100)[lengths(bamTop100)>0]

## files will be output into outPath
outPath = "splited"
dir.create(outPath)

## shift the coordinates of 5'ends of alignments in the bam file
library(BSgenome.Hsapiens.UCSC.hg38)
seqlev = "chr1" ## subsample data for quick run
which = as(seqinfo(Hsapiens)[seqlev], "GRanges")
gal = readBamFile(bamfile, tag=tags, which=which, asMates=TRUE, bigFile=TRUE)
shiftedBamfile = file.path(outPath, "shifted.bam")
gal1 = shiftGAlignmentsList(gal, outbam=shiftedBamfile)

txs = transcripts(TxDb.Hsapiens.UCSC.hg38.knownGene)

## run program for chromosome 1 only
txs <- txs[seqnames(txs) %in% "chr1"]
genome <- Hsapiens
## split the reads into NucleosomeFree, mononucleosome,
## dinucleosome and trinucleosome.
## and save the binned alignments into bam files.
objs <- splitGAlignmentsByCut(gal1, txs=txs, genome=genome, outPath = outPath,
                              conservation=phastCons100way.UCSC.hg38)
## list the files generated by splitGAlignmentsByCut.
dir(outPath)


#######################################################################################################################################################
##### Library complexity plot and table.
#######################################################################################################################################################
histFile = readsDupFreq(bamFile=bamfile, index =bamfile)
pdf(paste0(bamfile,"_library_complexity.pdf"), width=8, height=5)
complexity <- estimateLibComplexity(histFile=histFile, times=1, interpolate.sample.sizes=seq(0.1, 1, by=0.01), extrapolate.sample.sizes=seq(5, 20, by=5))
dev.off()
write.table(complexity, paste0(bamfile, "_complexity.txt"), sep ="\t", quote=F, row.names=FALSE)

#######################################################################################################################################################
##### Fragment size distribution plot
#######################################################################################################################################################
pdf(paste0(bamfile.sample.ID, "_fragment_size_distribution.pdf"),width =10, height=8)
fragSize <- fragSizeDist(bamFiles=bamfile, bamFiles.labels=bamfile.sample.ID)
dev.off()

#######################################################################################################################################################
##### Transcription Start Site Enrichment Score plot.
#######################################################################################################################################################
tsse <- TSSEscore(gal1, txs)
pdf(paste0(bamfile.sample.ID, "_transcription_start_site.pdf"), width =10, height=8)
plot(100*(-9:10-.5), tsse$values, type="b", xlab="distance to TSS",ylab="aggregate TSS score")
dev.off()

#######################################################################################################################################################
##### Heat map plot.
#######################################################################################################################################################

## calculate the signals around TSSs.
NTILE <- 101
dws <- ups <- 1010
sigs <- enrichedFragments(gal=objs[c("NucleosomeFree",
                                     "mononucleosome",
                                     "dinucleosome",
                                     "trinucleosome")],
                          TSS=TSS,
                          librarySize=librarySize,
                          seqlev=seqlev,
                          TSS.filter=0.5,
                          n.tile = NTILE,
                          upstream = ups,
                          downstream = dws)
## log2 transformed signals
sigs.log2 <- lapply(sigs, function(.ele) log2(.ele+1))
#plot heatmap
pdf(paste0(bamfile.sample.ID, "_heat_map.pdf"), width =10, height=8)
featureAlignedHeatmap(sigs.log2, reCenterPeaks(TSS, width=ups+dws),zeroAt=.5, n.tile=NTILE)
dev.off()

#######################################################################################################################################################
##### Feature aligned distribution plot.
#######################################################################################################################################################
pdf(paste0(bamfile.sample.ID, "_feature_aligned_distribution.pdf"),width =10, height=8)
out <- featureAlignedDistribution(sigs, reCenterPeaks(TSS, width=2020),zeroAt=.5, n.tile=101, type="l", ylab="Averaged coverage")
range01 <- function(x){(x-min(x))/(max(x)-min(x))}
out <- apply(out, 2, range01)
matplot(out, type="l", xaxt="n",xlab="Position (bp)",ylab="Fraction of signal")
axis(1, at=seq(0, 100, by=10)+1,labels=c("-1K", seq(-800, 800, by=200), "1K"), las=2)
abline(v=seq(0, 100, by=10)+1, lty=2, col="gray")
dev.off()

